version: '3.3'
services:
    backend:
        network_mode: "host"
        build:
          context: ./backend
        container_name: arxiv_backend
        ports:
            - "5000:5000"
        environment:
            - PYTHONUNBUFFERED=1
    frontend:
        network_mode: "host"
        build:
          context: ./frontend
        container_name: arxiv_frontend
    neo4j:
        network_mode: "host"
        build:
          context: ./db
        container_name: arxiv_neo4j
