version: '3.3'
services:
    backend:
        network_mode: "host"
        build:
          context: ./backend
        container_name: arxiv_backend
        depends_on:
            - neo4j
        ports:
            - "5000:5000"
        environment:
            - PYTHONUNBUFFERED=1
    frontend:
        network_mode: "host"
        build:
          context: ./frontend
        container_name: arxiv_frontend
    neo4j:
        network_mode: "host"
        build:
          context: ./db
        environment:
          NEO4J_AUTH: neo4j/password
        container_name: arxiv_neo4j
        restart: always
        ports:
            - "7474:7474"
            - "7687:7687"
