version: '3.3'
services:
    backend:
        build:
          context: ./backend
        container_name: arxiv_backend
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
            - neo4j
    frontend:
        build:
          context: ./frontend
        ports:
            - "3000:3000" 
        container_name: arxiv_frontend
        depends_on:
            - backend
    neo4j:
        image: neo4j:4.2.0
        container_name: arxiv_neo4j
        environment:
            NEO4J_AUTH: neo4j/password
